- name: Playin with ansible on openshift
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: play with user
      user:
        name: tree
        state: present 
      become: yes
      
